# Generated by Django 4.2.16 on 2026-04-18 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_category_image'),
        ('coupon', '0003_remove_coupon_discount_remove_coupon_min_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên chương trình')),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=300, verbose_name='Mô tả ngắn')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Nội dung chi tiết')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='promotions/', verbose_name='Ảnh banner')),
                ('discount_type', models.CharField(choices=[('percent', 'Giảm theo phần trăm'), ('amount', 'Giảm theo số tiền'), ('label', 'Nhãn ưu đãi')], default='percent', max_length=20, verbose_name='Loại ưu đãi')),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá trị ưu đãi')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nhãn hiển thị')),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Ưu đãi nổi bật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='coupon.coupon', verbose_name='Mã giảm giá liên kết')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='core.product', verbose_name='Sản phẩm áp dụng')),
            ],
            options={
                'verbose_name': 'Khuyến mãi',
                'verbose_name_plural': 'Khuyến mãi',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
