# Generated by Django 6.0.3 on 2026-04-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Liên hệ với chúng tôi', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('hotline', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('working_hours', models.CharField(blank=True, max_length=255)),
                ('map_embed_url', models.TextField(help_text='Dán link Google Maps embed')),
                ('support_1', models.CharField(blank=True, max_length=255)),
                ('support_2', models.CharField(blank=True, max_length=255)),
                ('support_3', models.CharField(blank=True, max_length=255)),
                ('support_4', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tin nhắn liên hệ', 'verbose_name_plural': 'Tin nhắn liên hệ'},
        ),
    ]
