# Generated by Django 6.0.3 on 2026-04-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactinfo_alter_contactmessage_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
