# Generated by Django 6.0.3 on 2026-04-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review_image'),
        ('core', '0005_contactinfo'),
    ]

    operations = [
    ]
