# Generated by Django 6.0.3 on 2026-04-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hotdeal_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hotdeal_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hotdeal',
            field=models.BooleanField(default=False),
        ),
    ]
