# Generated by Codex on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_discount_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotDealCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('discount_percent', models.PositiveSmallIntegerField()),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='hotdeal_campaigns', to='core.product')),
            ],
            options={
                'ordering': ['-priority', 'start_at', '-created'],
            },
        ),
    ]
