# Generated by Codex on 2026-04-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_category_slug_alter_product_slug'),
        ('core', '0012_hotdealcampaign'),
    ]

    operations = []
