# Generated by Codex on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_remove_coupon_discount_remove_coupon_min_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
