# Generated by Codex on 2026-04-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0015_order_stock_deducted'),
        ('coupon', '0004_coupon_min_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifted_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='source_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifted_coupons', to='orders.order'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='gift_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
