# Generated by Django 4.2.16 on 2026-04-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Tên doanh nghiệp')),
                ('business_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên cửa hàng / thương hiệu')),
                ('tax_code', models.CharField(max_length=50, verbose_name='Mã số thuế')),
                ('license_number', models.CharField(max_length=100, verbose_name='Số giấy phép kinh doanh')),
                ('issued_by', models.CharField(max_length=255, verbose_name='Nơi cấp')),
                ('issue_date', models.DateField(verbose_name='Ngày cấp')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('representative', models.CharField(blank=True, max_length=255, null=True, verbose_name='Người đại diện')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả thêm')),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Giấy phép kinh doanh',
                'verbose_name_plural': 'Giấy phép kinh doanh',
            },
        ),
        migrations.CreateModel(
            name='PolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('return', 'Chính sách đổi trả'), ('shipping', 'Chính sách vận chuyển'), ('warranty', 'Chính sách bảo hành'), ('privacy', 'Chính sách bảo mật'), ('terms', 'Điều khoản sử dụng')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trang chính sách',
                'verbose_name_plural': 'Trang chính sách',
                'ordering': ['policy_type'],
            },
        ),
    ]
