# Generated by Django 4.2.16 on 2026-04-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policypage',
            name='policy_type',
            field=models.CharField(choices=[('return', 'Chính sách đổi trả'), ('shipping', 'Chính sách vận chuyển'), ('warranty', 'Chính sách bảo hành'), ('privacy', 'Chính sách bảo mật'), ('terms', 'Điều khoản sử dụng'), ('payment', 'Quy trình mua hàng và thanh toán'), ('complaint', 'Khiếu nại và giải quyết tranh chấp')], max_length=20, unique=True),
        ),
    ]
