# Generated by Django 6.0.3 on 2026-03-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('support', 'Hỗ trợ đơn hàng'), ('consult', 'Tư vấn sản phẩm'), ('feedback', 'Góp ý'), ('complaint', 'Khiếu nại')], default='support', max_length=20),
        ),
    ]
