from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

app_name = 'admin'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='admin/pages/authentication/sign-in.html', redirect_authenticated_user=True), name='login'),
    path('', views.index, name='index'),
    path('blog/', views.blog_list, name='blog_list'),
    path('blog/add/', views.blog_add, name='blog_add'),
    path('blog/edit/<int:pk>/', views.blog_edit, name='blog_edit'),
    path('blog/delete/<int:pk>/', views.blog_delete, name='blog_delete'),
    # Blog Categories
    path('blog/categories/', views.blog_category_list, name='blog_category_list'),
    path('blog/categories/add/', views.blog_category_add, name='blog_category_add'),
    path('blog/categories/edit/<int:pk>/', views.blog_category_edit, name='blog_category_edit'),
    path('blog/categories/delete/<int:pk>/', views.blog_category_delete, name='blog_category_delete'),

    # Accounts / Customers
    path('accounts/', views.account_list, name='account_list'),
    path('accounts/add/', views.account_add, name='account_add'),
    path('accounts/edit/<int:pk>/', views.account_edit, name='account_edit'),
    path('accounts/delete/<int:pk>/', views.account_delete, name='account_delete'),

    # Legal
    path('legal/policies/', views.legal_policy_list, name='legal_policy_list'),
    path('legal/policies/add/', views.legal_policy_add, name='legal_policy_add'),
    path('legal/policies/edit/<int:pk>/', views.legal_policy_edit, name='legal_policy_edit'),
    path('legal/policies/delete/<int:pk>/', views.legal_policy_delete, name='legal_policy_delete'),
    path('legal/licenses/', views.legal_license_list, name='legal_license_list'),
    path('legal/licenses/add/', views.legal_license_add, name='legal_license_add'),
    path('legal/licenses/edit/<int:pk>/', views.legal_license_edit, name='legal_license_edit'),
    path('legal/licenses/delete/<int:pk>/', views.legal_license_delete, name='legal_license_delete'),
    path('ecommerce/category/', views.ec_category_list, name='ec_category_list'),
    path('ecommerce/category/add/', views.ec_category_add, name='ec_category_add'),
    path('ecommerce/category/edit/<int:pk>/', views.ec_category_edit, name='ec_category_edit'),
    path('ecommerce/category/delete/<int:pk>/', views.ec_category_delete, name='ec_category_delete'),
    path('ecommerce/contactinfo/', views.ec_contactinfo_list, name='ec_contactinfo_list'),
    path('ecommerce/contactinfo/add/', views.ec_contactinfo_add, name='ec_contactinfo_add'),
    path('ecommerce/contactinfo/edit/<int:pk>/', views.ec_contactinfo_edit, name='ec_contactinfo_edit'),
    path('ecommerce/contactinfo/delete/<int:pk>/', views.ec_contactinfo_delete, name='ec_contactinfo_delete'),
    path('ecommerce/policy/', views.ec_policy_list, name='ec_policy_list'),
    path('ecommerce/policy/add/', views.ec_policy_add, name='ec_policy_add'),
    path('ecommerce/policy/edit/<int:pk>/', views.ec_policy_edit, name='ec_policy_edit'),
    path('ecommerce/policy/delete/<int:pk>/', views.ec_policy_delete, name='ec_policy_delete'),
    path('ecommerce/product/', views.ec_product_list, name='ec_product_list'),
    path('ecommerce/product/add/', views.ec_product_add, name='ec_product_add'),
    path('ecommerce/product/edit/<int:pk>/', views.ec_product_edit, name='ec_product_edit'),
    path('ecommerce/product/delete/<int:pk>/', views.ec_product_delete, name='ec_product_delete'),
    path('ecommerce/review/', views.ec_review_list, name='ec_review_list'),
    path('ecommerce/review/add/', views.ec_review_add, name='ec_review_add'),
    path('ecommerce/review/edit/<int:pk>/', views.ec_review_edit, name='ec_review_edit'),
    path('ecommerce/review/delete/<int:pk>/', views.ec_review_delete, name='ec_review_delete'),
    path('ecommerce/contactmessage/', views.ec_contactmessage_list, name='ec_contactmessage_list'),
    path('ecommerce/contactmessage/add/', views.ec_contactmessage_add, name='ec_contactmessage_add'),
    path('ecommerce/contactmessage/edit/<int:pk>/', views.ec_contactmessage_edit, name='ec_contactmessage_edit'),
    path('ecommerce/contactmessage/delete/<int:pk>/', views.ec_contactmessage_delete, name='ec_contactmessage_delete'),
    path('ecommerce/wishlist/', views.ec_wishlist_list, name='ec_wishlist_list'),
    path('ecommerce/wishlist/add/', views.ec_wishlist_add, name='ec_wishlist_add'),
    path('ecommerce/wishlist/edit/<int:pk>/', views.ec_wishlist_edit, name='ec_wishlist_edit'),
    path('ecommerce/wishlist/delete/<int:pk>/', views.ec_wishlist_delete, name='ec_wishlist_delete'),
    path('ecommerce/order/', views.ec_order_list, name='ec_order_list'),
    path('ecommerce/order/add/', views.ec_order_add, name='ec_order_add'),
    path('ecommerce/order/edit/<int:pk>/', views.ec_order_edit, name='ec_order_edit'),
    path('ecommerce/order/delete/<int:pk>/', views.ec_order_delete, name='ec_order_delete'),
    path('ecommerce/coupon/', views.ec_coupon_list, name='ec_coupon_list'),
    path('ecommerce/coupon/add/', views.ec_coupon_add, name='ec_coupon_add'),
    path('ecommerce/coupon/edit/<int:pk>/', views.ec_coupon_edit, name='ec_coupon_edit'),
    path('ecommerce/coupon/delete/<int:pk>/', views.ec_coupon_delete, name='ec_coupon_delete'),
    path('ecommerce/promotion/', views.ec_promotion_list, name='ec_promotion_list'),
    path('ecommerce/promotion/add/', views.ec_promotion_add, name='ec_promotion_add'),
    path('ecommerce/promotion/edit/<int:pk>/', views.ec_promotion_edit, name='ec_promotion_edit'),
    path('ecommerce/promotion/delete/<int:pk>/', views.ec_promotion_delete, name='ec_promotion_delete'),
    path('ecommerce/banner/', views.ec_banner_list, name='ec_banner_list'),
    path('ecommerce/banner/add/', views.ec_banner_add, name='ec_banner_add'),
    path('ecommerce/banner/edit/<int:pk>/', views.ec_banner_edit, name='ec_banner_edit'),
    path('ecommerce/banner/delete/<int:pk>/', views.ec_banner_delete, name='ec_banner_delete'),

    
    path('socialaccount/', views.socialaccount_list, name='socialaccount_list'),
    path('socialaccount/create/', views.socialaccount_create, name='socialaccount_create'),
    path('socialaccount/<int:pk>/update/', views.socialaccount_update, name='socialaccount_update'),
    path('socialaccount/<int:pk>/delete/', views.socialaccount_delete, name='socialaccount_delete'),

    path('socialapp/', views.socialapp_list, name='socialapp_list'),
    path('socialapp/create/', views.socialapp_create, name='socialapp_create'),
    path('socialapp/<int:pk>/update/', views.socialapp_update, name='socialapp_update'),
    path('socialapp/<int:pk>/delete/', views.socialapp_delete, name='socialapp_delete'),

    path('sys-user/', views.core_user_list, name='core_user_list'),
    path('sys-user/create/', views.core_user_create, name='core_user_create'),
    path('sys-user/<int:pk>/update/', views.core_user_update, name='core_user_update'),
    path('sys-user/<int:pk>/delete/', views.core_user_delete, name='core_user_delete'),

    path('sys-group/', views.core_group_list, name='core_group_list'),
    path('sys-group/create/', views.core_group_create, name='core_group_create'),
    path('sys-group/<int:pk>/update/', views.core_group_update, name='core_group_update'),
    path('sys-group/<int:pk>/delete/', views.core_group_delete, name='core_group_delete'),

    path('sys-site/', views.core_site_list, name='core_site_list'),
    path('sys-site/create/', views.core_site_create, name='core_site_create'),
    path('sys-site/<int:pk>/update/', views.core_site_update, name='core_site_update'),
    path('sys-site/<int:pk>/delete/', views.core_site_delete, name='core_site_delete'),

    path('sys-email/', views.core_email_list, name='core_email_list'),
    path('sys-email/create/', views.core_email_create, name='core_email_create'),
    path('sys-email/<int:pk>/update/', views.core_email_update, name='core_email_update'),
    path('sys-email/<int:pk>/delete/', views.core_email_delete, name='core_email_delete'),

    path('sys-chat/', views.core_chat_list, name='core_chat_list'),
    path('sys-chat/create/', views.core_chat_create, name='core_chat_create'),
    path('sys-chat/<int:pk>/update/', views.core_chat_update, name='core_chat_update'),
    path('sys-chat/<int:pk>/delete/', views.core_chat_delete, name='core_chat_delete'),

    path('logout/', views.admin_logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
]
