# Generated by Django 6.0.3 on 2026-04-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_district_order_province_order_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toan khi nhan hang'), ('sepay', 'Thanh toan qua SePay')], default='cod', max_length=20),
        ),
    ]
