# Generated by Django 6.0.3 on 2026-04-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('sepay', 'Sepay (QR code)'), ('manual', 'Thanh toán thủ công / Admin duyệt')], default='sepay', max_length=20),
        ),
    ]
