# Generated by Django 4.2.11 on 2026-04-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_method'),
        ('orders', '0005_order_user'),
    ]

    operations = [
    ]
