# Generated by Django 4.2.11 on 2026-04-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_method'),
        ('orders', '0007_order_paid'),
    ]

    operations = [
    ]
