# Generated by Django 4.2.11 on 2026-04-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('confirmed', 'Chờ xác nhận'), ('preparing', 'Chờ lấy hàng'), ('shipping', 'Đang giao hàng'), ('completed', 'Đã giao hàng'), ('cancelled', 'Đã huỷ'), ('processing', 'Đang xử lý')], default='pending', max_length=20),
        ),
    ]
