# Generated by Django 6.0.3 on 2026-04-21 18:13

from django.db import migrations, models


def manual_to_cod(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(payment_method='manual').update(payment_method='cod')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_add_order_status_stages'),
    ]

    operations = [
        migrations.RunPython(manual_to_cod, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('sepay', 'Sepay (QR code)'), ('cod', 'Thanh toán khi nhận hàng')], default='sepay', max_length=20),
        ),
    ]
